export interface PrestadorForCreation{
  razaoSocial: string,
  nomeFantasia: string,
  sobre: string,
  tipoPessoa: string,
  cnpjCpf: string,
  endereco: string,
  complemento: string,
  bairro: string,
  cidade: string,
  cep: string,
  numero: string,
  atuacao: string,
  especializacao: string,
  imagem: string,
  urlSite: string,
  statusId: number,
  usuarioId: string,
}
